#!/bin/bash

RUN_DIR=/var/vcap/sys/run/credhub
LOG_DIR=/var/vcap/sys/log/credhub
PIDFILE=${RUN_DIR}/pid
RUNAS=vcap

export JAVA_HOME=/var/vcap/packages/openjdk_1.8.0/jdk
export PATH=$JAVA_HOME/bin:$PATH

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    cd /var/vcap/packages/credhub
    exec chpst -u $RUNAS:$RUNAS java -Dspring.config.location=/var/vcap/jobs/credhub/config/application.properties -jar *.jar

    ;;

  stop)
    kill -9 `cat $PIDFILE`
    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}"

    ;;

esac
