#!/bin/bash

RUN_DIR=/var/vcap/sys/run/credhub
LOG_DIR=/var/vcap/sys/log/credhub
PIDFILE=${RUN_DIR}/pid
RUNAS=vcap

export JAVA_HOME=/var/vcap/packages/openjdk_1.8.0/jdk
export PATH=$JAVA_HOME/bin:$PATH

exec > >(tee -a >(logger -p user.info -t vcap.$(basename $0).stdout)   | grep -Ev '^$' | awk -W interactive '{ system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }' >> ${LOG_DIR}/credhub.stdout.log)
exec 2> >(tee -a >(logger -p user.error -t vcap.$(basename $0).stderr) | grep -Ev '^$' | awk -W interactive '{ system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }' >> ${LOG_DIR}/credhub.stderr.log)

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    cd /var/vcap/packages/credhub
    exec chpst -u $RUNAS:$RUNAS java \
        -Dspring.config.location=/var/vcap/jobs/credhub/config/application.properties \
        -Dlog4j.configurationFile=/var/vcap/jobs/credhub/config/log4j2.properties \
        -Djava.security.egd=file:/dev/urandom \
        -ea -jar *.jar
    ;;

  stop)
    kill -9 `cat $PIDFILE`
    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}"

    ;;

esac
