#!/bin/sh

echo "Preparing to ship .........."


function set_bash_error_handling() {
    set -euo pipefail
}

function go_to_project_root_directory() {
    local -r hook_dir=$( dirname "${BASH_SOURCE[0]}")

    cd "$hook_dir/.."
}

function check_ssh_key() {
    if ! ssh-add -l >/dev/null; then
        echo "No SSH key loaded! Please run vkl."
        exit 1
    fi
}

function run_linters() {
    ./scripts/lint.sh
}

function run_tests() {
    ./scripts/run_tests.sh
}

function main() {
    set_bash_error_handling
    go_to_project_root_directory
    check_ssh_key

    run_linters
    run_tests
}

main
